compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@uniswap/swap-router-contracts@*":
    peerDependenciesMeta:
      hardhat:
        optional: true
  "@uniswap/v3-periphery@*":
    peerDependenciesMeta:
      hardhat:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
