name: Build (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      YARN_CACHE_FOLDER: ./.yarn/cache
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
      - name: install
        run: yarn install
      - name: build
        run: yarn xy build
  test:
    runs-on: ubuntu-latest
    env:
      YARN_CACHE_FOLDER: ./.yarn/cache
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
      - name: install
        run: yarn install
      - name: copy env file
        run: cp .example.env .env
      - name: test
        run: yarn test --forceExit --coverage
        env:
          # Current max memory size of Linux hosted runner is 7 GB
          # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
          NODE_OPTIONS: "--max-old-space-size=5120"
      - name: format code coverage
        uses: xylabs/action-code-climate-test-reporter@v1.0.0
        with:
          subcommand: "format-coverage -t lcov ./coverage/lcov.info"
      # TODO: Setup coverage project on Code Climate
      # - name: upload code coverage
      #   uses: xylabs/action-code-climate-test-reporter@v1.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     subcommand: "upload-coverage"
